# python run.py main --run_name codecontests-gpt35 --configs configs/codecontests-gpt35.yaml run &&
# python run.py eval run --run_name codecontests-gpt35 --dataset_type deepmind/code_contests --timeout 6
target.dataset_type:
  desc: "Dataset type for the target"
  value: "deepmind/code_contests"
target.dataset_split:
  desc: "Dataset split for the target"
  value: "test"

example:
  desc: "Example to use"
  value:
    code:
      dataset_type: "openai_humaneval"
      path: "data/codecontests-requirements.json"

llm:
  desc: "Language model to use"
  value:
    code:
      model: "gpt-35-turbo-16k"
      max_tokens: 1024
      top_p: 0.95
      temperature: 0.8
      n: 10
      max_retries: 1000000

chain.model:
  desc: "Chain model to use"
  value: "multi_turn"
chain.kwargs:
  desc: "Chain kwargs to use"
  value:
    graph:
      code: []
