# python run.py main --run_name humaneval-ours-notime --configs configs/humaneval-ours-notime.yaml run &&
# python run.py eval run --run_name humaneval-ours-notime --ref_path data/humaneval_nfr.json --k [1,2,5,10] && 
# python run.py eval run --run_name humaneval-ours-notime --ref_path results/humaneval_nf-notime/result.json --k [1,2,5,10] --sub_dir notime --ref_key gen_tc && 
# python run.py eval run --run_name humaneval-ours-notime --ref_path results/humaneval_nf-time/result.json --k [1,2,5,10] --sub_dir time --ref_key gen_tc
# python run.py eval run --run_name humaneval-ours-notime --ref_path data/humaneval_nfr.json --k [1,2,5,10] --sub_dir reliability --ignore_assertion_errors True
# python run.py eval run --run_name humaneval-ours-notime --ref_path results/humaneval_nf-fr/result.json --k [1,2,5,10] --sub_dir fr --ref_key gen_tc
# python run.py eval run --run_name humaneval-ours-notime --sub_dir robustness --ref_path results/humaneval_nf-robustness/result.json --ref_key gen_tc
# python run.py eval run --run_name humaneval-ours-notime --sub_dir maintainability --ref_path results/humaneval_nf-maintainability/result.json --ref_key gen_tc
target.dataset_type:
  desc: "Dataset type for the target"
  value: "openai_humaneval"
target.dataset_split:
  desc: "Dataset split for the target"
  value: "test"

example:
  desc: "Example to use"
  value:
    draft_plan:
      dataset_type: "openai_humaneval"
      path: "data/humaneval_tc_with_requirements.json"
    requirements:
      dataset_type: "openai_humaneval"
      path: "data/humaneval_tc_with_requirements.json"
    final_plan:
      dataset_type: "openai_humaneval"
      path: "data/humaneval_tc_with_requirements.json"
    code:
      dataset_type: "openai_humaneval"
      path: "data/humaneval_tc_with_requirements.json"

llm:
  desc: "Language model to use"
  value:
    draft_plan:
      model: "gpt-35-turbo-16k"
      max_tokens: 1024
      top_p: 0.95
      temperature: 0.8
      n: 10
      max_retries: 1000000
    requirements:
      model: "gpt-35-turbo-16k"
      max_tokens: 1024
      top_p: 1
      temperature: 0
      n: 1
      max_retries: 1000000
    final_plan:
      model: "gpt-35-turbo-16k"
      max_tokens: 1024
      top_p: 1
      temperature: 0
      n: 1
      max_retries: 1000000
    code:
      model: "gpt-35-turbo-16k"
      max_tokens: 1024
      top_p: 1
      temperature: 0
      n: 1
      max_retries: 1000000

chain.model:
  desc: "Chain model to use"
  value: "multi_turn"
chain.kwargs:
  desc: "Chain kwargs to use"
  value:
    graph:
      draft_plan: []
      requirements: ["draft_plan"]
      requirements_selector: ["requirements"]
      final_plan: ["draft_plan", "requirements_selector"]
      code: ["draft_plan", "requirements_selector", "final_plan"]
    parts:
      requirements: ["agnostic", "fr", "io", "expected", "edge", "nfr", "sqrs", "robustness", "reliability", "maintainability"]
